annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/kube-version: '>= 1.30.0-0 < 1.33.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.11.0-0 < 2.12.0-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: v3.1.0
created: "2025-07-02T14:21:32.509991222-03:00"
description: Prometheus Federator - installs rancher-project-monitoring in project
  namespaces.
digest: 656ab6bab96ea8a2114ca24d839a5db193b54838c68e8285016e135de063dc34
icon: file://assets/logos/prometheus-federator.svg
keywords:
- prometheus
- monitoring
- project-monitoring
maintainers:
- email: alexandre.lamarre@suse.com
  name: Alexandre
- email: dan.pock@suse.com
  name: Dan
- email: julia.suriano@suse.com
  name: Julia
name: prometheus-federator
urls:
- oci://zot.192.168.5.1.traefik.me:8443/rancher-charts/prometheus-federator:106.0.2_up3.1.0
version: 106.0.2+up3.1.0
