annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/kube-version: '>= 1.31.0-0 < 1.34.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.12.0-0 < 2.13.0-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: v4.2.1
created: "2025-11-20T21:51:04.390287994-03:00"
description: Prometheus Federator - installs rancher-project-monitoring in project
  namespaces.
digest: 58238e422d16e2bac78ab5d4bba22839ddacbe6bf4621a89923a00481ae5fadb
icon: file://assets/logos/prometheus-federator.svg
keywords:
- prometheus
- monitoring
- project-monitoring
maintainers:
- email: alexandre.lamarre@suse.com
  name: Alexandre
- email: dan.pock@suse.com
  name: Dan
- email: julia.suriano@suse.com
  name: Julia
name: prometheus-federator
urls:
- oci://zot.192.168.5.1.traefik.me:8443/rancher-charts/prometheus-federator:107.1.2_up4.2.1
version: 107.1.2+up4.2.1
