annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/kube-version: '>= 1.33.0-0 < 1.36.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.14.0-0 < 2.15.0-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: v6.0.0
created: "2026-03-23T14:37:35.063064943-03:00"
description: Prometheus Federator - installs rancher-project-monitoring in project
  namespaces.
digest: 4da6c5cd6fd918c85903f8a6f26ea1547b896481d1f4fa3181c0e6c805c0caea
icon: file://assets/logos/prometheus-federator.svg
keywords:
- prometheus
- monitoring
- project-monitoring
maintainers:
- email: alexandre.lamarre@suse.com
  name: Alexandre
- email: dan.pock@suse.com
  name: Dan
- email: julia.suriano@suse.com
  name: Julia
name: prometheus-federator
urls:
- oci://zot.192.168.5.1.traefik.me:8443/rancher-charts/prometheus-federator:109.0.0+up6.0.0
version: 109.0.0+up6.0.0
