annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>=1.16.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>=2.6.99-9 < 2.7.0-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: 0.2.1
created: "2024-06-21T15:41:01.292928959-03:00"
dependencies:
- condition: helmProjectOperator.enabled
  name: helmProjectOperator
  repository: file://./charts/helmProjectOperator
description: Prometheus Federator
digest: e1358a7551d8617c63776324a6beab3938a5a1f7ae31db2768cd0cbba649888a
icon: https://raw.githubusercontent.com/rancher/prometheus-federator/main/assets/logos/prometheus-federator.svg
name: prometheus-federator
urls:
- oci://zot.192.168.5.1.traefik.me:8443/rancher-charts/prometheus-federator:2.0.0_up0.2.1
version: 2.0.0+up0.2.1
