annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.27.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: 0.3.2
created: "2024-06-21T15:40:56.316248684-03:00"
dependencies:
- condition: helmProjectOperator.enabled
  name: helmProjectOperator
  repository: file://./charts/helmProjectOperator
description: Prometheus Federator
digest: a357faecb603c054fc3b9ff9859202b833345c871b28fc2cbd665f6be7645e52
icon: https://raw.githubusercontent.com/rancher/prometheus-federator/main/assets/logos/prometheus-federator.svg
name: prometheus-federator
urls:
- oci://zot.192.168.5.1.traefik.me:8443/rancher-charts/prometheus-federator:3.0.0+up0.3.3
version: 3.0.0+up0.3.3
