url: https://github.com/rancher/cis-operator.git
version: 6.2.0
releaseBranch: release/v1.2
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/cis-operator.git
      releaseBranch: release/v1.2
      subdirectory: crds
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
