url: https://github.com/rancher/cis-operator.git
version: 6.2.0
branch: release/v1.2
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
