url: github.coim/kube-logging/logging-operator.git
commit: ebf7ec008e8c1d5dbc7a8454d4a209153a4ccca7
subdirectory: charts/logging-operator
version: 102.0.3
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
