name: Charts-Release-Validations

on:
  pull_request:
    branches:
      - release-v*

jobs:
  build:
    name: Checkpoint 0 - release.yaml validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4

      - name: Checkout PR
        run: gh pr checkout ${{ github.event.pull_request.number }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout into branch
        run: git checkout -b staging-pr-workflow

      - name: Pull scripts
        run: make pull-scripts

      - name: Validate Charts Release
        run: make validate-release-charts BRANCH=${{ github.event.pull_request.base.ref }} GH_TOKEN=${{ secrets.GITHUB_TOKEN }} PR_NUMBER=${{ github.event.pull_request.number }}
